include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.gen.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
  errors:
    cancel_subscriptions: warning
    avoid_relative_lib_imports: warning
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    invalid_annotation_target: ignore
    avoid_dynamic_calls: ignore
    avoid_positional_boolean_parameters: ignore
    use_key_in_widget_constructors: ignore

linter:
  rules:
    sort_pub_dependencies: true
    cancel_subscriptions: true