name: test_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  easy_debounce: ^2.0.3
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  synchronized: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^6.0.0
